defaults:
  - _self_
  - experiments: null



seed: null
name: null
version: null

ckpt_ver: null
result_dir: "./results"

machine: null

overwrite_embed: false
overwrite_image: false

metric: null
vis_type: null
embed_key: null

extract_items: []

trans_exec: true
trans_overwrite: false
vis_exec: true
vis_overwrite: false


hydra:
  output_subdir: .hydra_umap
  run:
    dir: ${result_dir}/${name}/${version}_${seed}/output/${ckpt_ver}/${machine}
