defaults:
  - _self_
  - experiments: null



seed: null
dcase: null
name: null
version: null

infer_ver: null
result_dir: "./results"

machine: null


metric: null
embed_key: null

extract_items: []

overwrite: false


hydra:
  output_subdir: .hydra_umap
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}_${seed}/output/${infer_ver}/${machine}
