
batch_size: 256
sr: 16000
num_workers: 0


train:
  dataloader:
    batch_size: ${datamodule.batch_size}
    num_workers: ${datamodule.num_workers}
    pin_memory: true
    shuffle: true
  dataset:
    tgt_class: asdkit.datasets.AudioFeatDataset
    path_selector_list:
      - "${data_dir}/formatted/${dcase}/raw/${machine}/train/*.wav"
    audio_feat_cfg: ${frontend.model_cfg.audio_feat_cfg}
  batch_sampler: null
  collator:
    tgt_class: asdkit.datasets.DCASEAudioFeatCollator
    shuffle: true
    label_dict_path: ${label_dict_path}


valid:
  dataloader:
    batch_size: ${datamodule.batch_size}
    num_workers: ${datamodule.num_workers}
    pin_memory: true
    shuffle: false
  dataset:
    tgt_class: asdkit.datasets.WaveDataset
    path_selector_list:
      - "${data_dir}/formatted/${dcase}/raw/${machine}/test/*.wav"
  batch_sampler: null
  collator:
    tgt_class: asdkit.datasets.DCASEWaveCollator
    sr: ${datamodule.sr}
    sec: ${dcase}
    shuffle: false
    label_dict_path: ${label_dict_path}

