
batch_size: 64
sr: 16000
sec: 18
num_workers: 4

train:
    dataloader:
        batch_size: ${datamodule.batch_size}
        num_workers: ${datamodule.num_workers}
        pin_memory: true
        shuffle: true
    dataset:
        path_selector_list:
            - "${data_dir}/${dcase}/all/raw/*/train/*.wav" # TODO: check this path
    batch_sampler: null
    collator:
        sr: ${datamodule.sr}
        sec: ${datamodule.sec}
        shuffle: true

