
batch_size: 64
sr: 16000
sec: 18
num_workers: 4

train:
    dataloader:
        batch_size: ${datamodule.batch_size}
        num_workers: ${datamodule.num_workers}
        pin_memory: true
        shuffle: true
    dataset:
        tgt_class: asdit.datasets.BasicDataset
        path_selector_list:
            - "${data_dir}/formatted/${dcase}/raw/*/train/*.wav"
    batch_sampler: null
    collator:
        tgt_class: asdit.datasets.BasicCollator
        sr: ${datamodule.sr}
        sec: ${datamodule.sec}
        need_feat: false
        shuffle: true

