defaults:
  - _self_
  - experiments: null



seed: null
name: null
version: null

ckpt_ver: null
result_dir: "./results"

backend: []

machine: null

overwrite: false

hydra:
  output_subdir: .hydra_score
  run:
    dir: ${result_dir}/${name}/${version}_${seed}/output/${ckpt_ver}/${machine}
