tgt_class: asdkit.frontends.BasicDisPLModel

optim_cfg:
  tgt_class: torch.optim.AdamW
  lr: 1.0e-4

lrscheduler_cfg: null

label_dict_path: ${label_dict_path}

model_cfg:
  extractor_cfg:
    tgt_class: asdkit.models.pretrained_models.eat.EATLoRA
    lora_cfg:
      r: 64
      target_modules: ["qkv"]
    embed_size: 256
    projection_type: "linear"
    model_cfg:
      ckpt_path: "pretrained_models/eat/EAT-base_epoch10_pt.pt"
      sr: ${datamodule.sr}
      sec: ${datamodule.sec}
      prediction_mode: "cls"
      specaug: false
  loss_cfg: {}
  label_to_lossweight_dict:
    main: 1
  augmentation_cfg_list: []
