tgt_class: asdit.frontends.BasicDisPLModel

optim_cfg:
  tgt_class: torch.optim.AdamW
  lr: 1.0e-4

scheduler_cfg: null
grad_cfg: {}


model_cfg:
  normalize: true
  extractor_cfg:
    tgt_class: asdit.models.eat.EATLoRA
    ckpt_path: "pretrained_models/eat/EAT-base_epoch10_pt.pt"
    lora_cfg:
      r: 64
      target_modules: ["qkv"]
    embed_size: 256
    last_layer: "linear"
    model_cfg: {}
  loss_cfg: {}
  label_to_lossratio_dict:
    main_label: 1
  augmentation_cfg_list: []
