tgt_class: asdit.frontends.BasicDisPLModel

optim_cfg:
  tgt_class: torch.optim.AdamW
  lr: 1.0e-3

scheduler_cfg: null
grad_cfg: {}


model_cfg:
  normalize: true
  extractor_cfg:
    tgt_class: asdit.models.multiresnet.MultiResNet
    sec: ${datamodule.sec}
    sr: ${datamodule.sr}
    use_fft: true
    stft_cfg_list:
      -
        sr: ${datamodule.sr}
        n_fft: 256
        hop_length: 128
        n_mels: null
        power: 1.0
        f_min: 200.0
        f_max: 8000.0
        temporal_norm: false
      -
        sr: ${datamodule.sr}
        n_fft: 1024
        hop_length: 512
        n_mels: null
        power: 1.0
        f_min: 200.0
        f_max: 8000.0
        temporal_norm: false
      -
        sr: ${datamodule.sr}
        n_fft: 4096
        hop_length: 2048
        n_mels: null
        power: 1.0
        f_min: 200.0
        f_max: 8000.0
        temporal_norm: false
    use_bias: false
    emb_base_size: 128
  loss_cfg: {}
  loss_label2lam_dict:
    main_label: 1
  augmentation_cfg_list:
    - tgt_class: asdit.augmentations.Mixup
      prob: 0.5
