tgt_class: asdit.frontends.BasicDisPLModel

optim_cfg:
  tgt_class: torch.optim.AdamW
  lr: 1.0e-4

lrscheduler_cfg: null

label_dict_path: ${label_dict_path}

model_cfg:
  extractor_cfg:
    tgt_class: asdit.models.pretrained_models.beats.BEATsLoRA
    lora_cfg:
      r: 64
      target_modules: ["q_proj", "v_proj"]
    embed_size: 256
    projection_type: "attn_stat_pool"
    model_cfg:
      ckpt_path: "pretrained_models/beats/BEATs_iter3.pt"
      sr: ${datamodule.sr}
      specaug: false
  loss_cfg: {}
  label_to_lossweight_dict:
    main: 1
  augmentation_cfg_list: []
