defaults:
    - _self_
    - datamodule: null
    - model: null
    - trainer: null
    - experiments: null

seed: 0
dcase: null
name: null
version: null
result_dir: "./results"
data_dir: "../data"

label_dict_path: {}

machine: null
model_ver: null

num_workers: 4
refresh_rate: 1
callback_opts:
  best:
    monitor: "train/main"
    filename: "epoch={epoch}-loss={train/main:.9f}"
    save_top_k: 1
    mode: "min"
    auto_insert_metric_name: false
  interval:
    monitor: "train/main"
    filename: "interval_epoch={epoch}-loss={train/main:.9f}"
    save_top_k: -1
    every_n_epochs: 4
    save_last: true
    auto_insert_metric_name: false
every_n_epochs_valid: 1


hydra:
    run:
        dir: ${result_dir}/${name}/${dcase}/${version}_${seed}/model/${model_ver}
