defaults:
  - _self_
  - experiments: null



seed: null
dcase: null
name: null
version: null

infer_ver: null
result_dir: "./results"

hmean_cfg_dict: {}
overwrite: false



hydra:
  output_subdir: .hydra_table
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}_${seed}/output/${infer_ver}
