defaults:
  - _self_
  - experiments: null



seed: null
name: null
version: null

ckpt_ver: null
result_dir: "./results"

hmean_cfg_dict: {}
dcase: null
overwrite: false



hydra:
  output_subdir: .hydra_table
  run:
    dir: ${result_dir}/${name}/${version}_${seed}/output/${ckpt_ver}
