defaults:
  - _self_
  - experiments: null



seed: null
dcase: null
name: null
version: null

infer_ver: null
result_dir: "./results"

metrics:
  - official
  # - s_auc
  # - t_auc
  # - mix_auc
overwrite: true



hydra:
  output_subdir: .hydra_table
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}/${seed}/output/${infer_ver}
