defaults:
  - _self_
  - experiments: null



device: cuda:0 #cpu #
seed: null
dcase: null
name: null
version: null

restore_or_scratch: null

scratch_frontend: null
restore_model_ver: null
restore_ckpt_ver: null

result_dir: "./results"
infer_ver: null

data_dir: "../data"

datamodule:
  train:
    dataloader:
      batch_size: 64
      num_workers: 0
      pin_memory: false
      shuffle: false
    collator:
      tgt_class: "asdit.datasets.DCASEWaveCollator"
      label_dict_path: {}
      sec: null
      sr: 16000
      shuffle: false
    dataset:
      tgt_class: "asdit.datasets.WaveDataset"
      path_selector_list:
        - "${data_dir}/formatted/${dcase}/raw/${machine}/train/*.wav"
    batch_sampler: null
  test:
    dataloader: ${datamodule.train.dataloader}
    collator: ${datamodule.train.collator}
    dataset:
      tgt_class: "asdit.datasets.WaveDataset"
      path_selector_list:
        - "${data_dir}/formatted/${dcase}/raw/${machine}/test/*.wav"
    batch_sampler: null


machine: null

extract_items:
  - "path"
  - "section"
  - "is_normal"
  - "is_target"
  - "embed.*"
  - "AS.*"


overwrite: false

hydra:
  output_subdir: .hydra_extract
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}/${seed}/output/${infer_ver}/${machine}
