defaults:
  - _self_
  - experiments: null



device: cuda:0 #cpu #
seed: null
dcase: null
name: null
version: null

resume_or_scratch: null

plmodel_cfg: null
model_ver: null
ckpt_ver: null

result_dir: "./results"
infer_ver: null

datamodule:
  dataloader_cfg:
    batch_size: 64
    num_workers: 0
  collator_cfg: {}
  dataset_cfg: {}
label_dict_path: {}

machine: null

extract_items:
  - "embed-.*"
  - "AS-.*"


overwrite: false

hydra:
  output_subdir: .hydra_extract
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}_${seed}/output/${infer_ver}/${machine}
