defaults:
  - _self_
  - datamodule: default
  - experiments: null



device: cuda:0 #cpu #
seed: null
dcase: null
name: null
version: null

restore_or_scratch: null

scratch_frontend: null
restore_model_ver: null
restore_ckpt_ver: null

result_dir: "./results"
infer_ver: null

data_dir: "../data"

machine: null

extract_items:
  - "path"
  - "section"
  - "is_normal"
  - "is_target"
  - "embed.*"
  - "AS.*"


overwrite: false

hydra:
  output_subdir: .hydra_extract
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}/${seed}/output/${infer_ver}/${machine}
