defaults:
  - _self_
  - experiments: null



seed: null
dcase: null
name: null
version: null

infer_ver: null
result_dir: "./results"

machine: null


metric: null
embed_key: "embed"

extract_items:
  - "path"
  - "section"
  - "is_normal"
  - "is_target"

overwrite: false


hydra:
  output_subdir: .hydra_visualize
  run:
    dir: ${result_dir}/${name}/${dcase}/${version}/${seed}/output/${infer_ver}/${machine}
