tgt_class: mypkgs.pl_models.BasicDisPLModel

optim_cfg:
  tgt_class: torch.optim.AdamW
  lr: 1.0e-3

scheduler_cfg: null
grad_cfg: {}


model_cfg:
  extractor_cfg:
    tgt_class: mypkgs.models.MultiResNet
    sec: ${datamodule.sec}
    sr: ${datamodule.sr}
    stft_cfg_list:
      -
        sr: ${datamodule.sr}
        n_fft: 1024
        hop_length: 512
        n_mels: null
        power: 1.0
        use_mel: false
        f_min: 200.0
        f_max: 8000.0
        temporal_norm: false
    use_bias: false
    emb_base_size: 128
  loss_cfg:
    tgt_class: mypkgs.models.losses.SCAdaCos
    n_subclusters: 16
    dynamic: false
    trainable: true
  loss_label2lam_dict: {}
  augmentation_cfg_list:
    - tgt_class: mypkgs.models.augmentations.Mixup
      prob: 0.5
  use_compile: false
