name: null
dcase: null
teacher_dir: null #raw_eat/0/output/last
output_label_name: null #raw_eat_kmeans_8

results_root_dir: ../../results/${name}
labels_root_dir: ../../labels/${name}
machinewise: true
model:
  tgt_class: models.KMeansRatioModel
  ratio: 0.008


hydra:
  output_subdir: .hydra_${output_label_name}
  run:
    dir: ${labels_root_dir}/${dcase}
  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/${output_label_name}.log
